### ISSUE TITLE
TCP(MySQL) Forwarding not responding

### ISSUE THREAD

**Issue by woshikie** [antoniomika/sish#100]
I'm trying to port forward a local mysql database.
This is my docker-compose.yml for my database instance
```
version: '3'

services:
  db:
    image: mysql:5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'Very Secure Password'
    ports:
      - '33306:3306'
    volumes:
      - ./mount:/var/lib/mysql
```
next, I setup my sish instance on a remote server with 
```
version: "3"
services:
  sish:
    image: antoniomika/sish:latest
    restart: always
    volumes:
      - ./sish/ssl:/ssl
      - ./sish/keys:/keys
      - ./sish/pubkeys:/pubkeys
    network_mode: host
    command: |
      --ssh-address=:22222
      --https-address=:20443
      --http-address=:20080
      --https=false
      --https-certificate-directory=/ssl
      --authentication-keys-directory=/pubkeys
      --private-key-location=/keys/ssh_key
      --domain=<my domain>
      --bind-random-subdomains=false
      --bind-random-ports=false
      --proxy-protocol=false
      --redirect-root=false
```
then, on my local server, i ran:
`ssh -R 3306:localhost:33306 <my domain> -p 22222`
The ssh tunnel service started but when I try to connect to to my server though MySQL Workbench, it timed out.
Tried to tunnel with Ngrok and it works.
It seemed like the no packets are passed through the tunnel

I have other HTTP tunnels running on the sish instance on the remote server too.
HTTP tunnels work very well.

I started using SISH a couple months ago and all the tunnels worked well.
This only happened after I updated to the latest version

EDIT:
Confirmed working with version 0.4.0
<details>
<summary>The docker config:</summary>

```
    volumes:
      - ./sish/ssl:/ssl
      - ./sish/keys:/keys
      - ./sish/pubkeys:/pubkeys
    network_mode: host
    command: |
      -sish.addr=:22222
      -sish.https=:30443
      -sish.http=:30080
      -sish.httpsenabled=false
      -sish.keysdir=/pubkeys
      -sish.pkloc=/keys/ssh_key
      -sish.bindrandom=false
      -sish.domain=<mydomain>
      -sish.forcerandomsubdomain=false
```

</details>
