### ISSUE TITLE
SSH Connection dropped

### ISSUE THREAD

**Issue by solaris7x** [antoniomika/sish#113]
I am using  docker-compose for sish host to ssh into a ubuntu server , I can authenticate and log in to the server but the connection is dropped within few secs 
Normal SSH working fine thus do I need to modify some sshd config for using sish?
Sish Host docker compose config 
```yaml
version: "3.7"

services:
  sish:
    image: antoniomika/sish:latest
    container_name: sish
    volumes:
      - ./pubkeys:/pubkeys
      - ./keys:/keys
      - ./ssl:/ssl
    command: |
      --ssh-address=:4022
      --http-address=:4080
      --https-address=:4443
      --https=false
      --https-certificate-directory=/ssl
      --private-key-location=/keys/together.pem
      --private-key-passphrase='qwerty123'
      --bind-random-ports=false
      --bind-random-subdomains=false
    network_mode: host
    restart: always
```
SSL directory is empty 

Ubuntu Server
```
ssh -vNR 4122:localhost:22 sish.host.xyz -p 4022
```
Output: 
```
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /home/coffee/.ssh/id_rsa
debug1: Will attempt key: /home/coffee/.ssh/id_dsa
debug1: Will attempt key: /home/coffee/.ssh/id_ecdsa
debug1: Will attempt key: /home/coffee/.ssh/id_ed25519
debug1: Will attempt key: /home/coffee/.ssh/id_xmss
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentication succeeded (none).
Authenticated to sish.host.xyz ([11.11.11.11]:4022).
debug1: Remote connections from LOCALHOST:4122 forwarded to local address localhost:22
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype keepalive@sish want_reply 1

```

Client:
```
ssh coffee@sish.host.xyz -vp 4122
```
Output:
```
Last login: Wed Jul 15 17:28:17 2020 from 127.0.0.1
coffee@sage:~$ debug1: channel 0: free: client-session, nchannels 1
Connection to sish.host.xyz closed by remote host.
Connection to sish.host.xyz closed.
Transferred: sent 2676, received 3528 bytes, in 6.2 seconds
Bytes per second: sent 428.2, received 564.5
debug1: Exit status -1
```
